import type { Finca, Producto } from './types'

export const SEED_FINCAS: Omit<Finca, 'id'>[] = [
  {
    nombre: 'Finca La Esperanza',
    propietario: 'Carlos Pertuz',
    propietarioUid: 'seed-uid-1',
    año: 2005,
    ubicacion: 'Sabanalarga, Atlántico',
    tipoCultivo: 'Hortalizas y verduras',
    telefono: '+57 300 123 4567',
    rating: 4.8,
    descripcion: 'Somos una familia campesina que lleva más de 18 años cultivando hortalizas orgánicas en el corazón del Atlántico. Usamos técnicas ancestrales combinadas con innovación para ofrecerte los productos más frescos.',
    imagenURL: 'https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?w=800&q=80',
    videoURL: '',
  },
  {
    nombre: 'Agroparque Los Manantiales',
    propietario: 'María Orozco',
    propietarioUid: 'seed-uid-2',
    año: 2010,
    ubicacion: 'Manatí, Atlántico',
    tipoCultivo: 'Frutas tropicales',
    telefono: '+57 311 234 5678',
    rating: 4.9,
    descripcion: 'En Los Manantiales cultivamos las mejores frutas tropicales del Caribe colombiano. Nuestros árboles de mango, guanábana y maracuyá producen frutas de calidad exportación que ahora llegan directamente a tu mesa.',
    imagenURL: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80',
    videoURL: '',
  },
  {
    nombre: 'El Vergel del Río',
    propietario: 'José Barrios',
    propietarioUid: 'seed-uid-3',
    año: 1998,
    ubicacion: 'Ponedera, Atlántico',
    tipoCultivo: 'Plátano y yuca',
    telefono: '+57 320 345 6789',
    rating: 4.6,
    descripcion: 'Con más de 25 años de tradición, El Vergel del Río es pionero en el cultivo sostenible de plátano y yuca. Abastecemos a familias y restaurantes que valoran el sabor auténtico del campo costeño.',
    imagenURL: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=800&q=80',
    videoURL: '',
  },
  {
    nombre: 'Finca Santa Rosa',
    propietario: 'Ana Hernández',
    propietarioUid: 'seed-uid-4',
    año: 2015,
    ubicacion: 'Usiacurí, Atlántico',
    tipoCultivo: 'Tomate y pimentón',
    telefono: '+57 315 456 7890',
    rating: 4.7,
    descripcion: 'Santa Rosa es una finca de nueva generación liderada por una mujer campesina. Cultivamos tomates y pimentones bajo técnicas de agricultura regenerativa que cuidan el suelo y el medio ambiente.',
    imagenURL: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80',
    videoURL: '',
  },
]

export const SEED_PRODUCTOS: Omit<Producto, 'id'>[] = [
  // Finca 1 — La Esperanza (índice 0)
  {
    fincaId: 'finca-0',
    fincaNombre: 'Finca La Esperanza',
    nombre: 'Lechuga Criolla Orgánica',
    categoria: 'Hortalizas',
    precio: 2500,
    unidad: 'unidad',
    stock: 80,
    descripcion: 'Lechuga fresca recién cortada, sin pesticidas ni agroquímicos. Cultivada con agua limpia de pozo artesiano.',
    beneficios: ['Rica en vitamina K', 'Baja en calorías', 'Hidratante natural', 'Libre de pesticidas'],
    imagenURL: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=600&q=80',
  },
  {
    fincaId: 'finca-0',
    fincaNombre: 'Finca La Esperanza',
    nombre: 'Tomate Chonto Fresco',
    categoria: 'Hortalizas',
    precio: 4200,
    unidad: 'kg',
    stock: 120,
    descripcion: 'Tomate chonto maduro en palo, con ese sabor intenso y dulce que solo el campo atlántico puede ofrecer.',
    beneficios: ['Alto en licopeno', 'Fuente de vitamina C', 'Antioxidante natural', 'Sabor auténtico'],
    imagenURL: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=600&q=80',
  },
  {
    fincaId: 'finca-0',
    fincaNombre: 'Finca La Esperanza',
    nombre: 'Cilantro y Hierbas Aromáticas',
    categoria: 'Hierbas',
    precio: 1800,
    unidad: 'manojo',
    stock: 60,
    descripcion: 'Mix de hierbas frescas: cilantro, cebolla de rama y ají criollo. La base de la cocina costeña auténtica.',
    beneficios: ['Digestivo natural', 'Antioxidante', 'Aroma inigualable', 'Sin conservantes'],
    imagenURL: 'https://images.unsplash.com/photo-1437218374153-7f5fe5a4f040?w=600&q=80',
  },
  // Finca 2 — Los Manantiales (índice 1)
  {
    fincaId: 'finca-1',
    fincaNombre: 'Agroparque Los Manantiales',
    nombre: 'Mango Tommy Maduro',
    categoria: 'Frutas',
    precio: 6500,
    unidad: 'docena',
    stock: 50,
    descripcion: 'Mangos Tommy Atkins en su punto perfecto de maduración. Dulces, jugosos y con el aroma característico del trópico.',
    beneficios: ['Rico en vitamina A', 'Fuente de fibra', 'Mejora la digestión', 'Alto en antioxidantes'],
    imagenURL: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&q=80',
  },
  {
    fincaId: 'finca-1',
    fincaNombre: 'Agroparque Los Manantiales',
    nombre: 'Maracuyá Tropical',
    categoria: 'Frutas',
    precio: 5000,
    unidad: 'kg',
    stock: 40,
    descripcion: 'Maracuyá recién cosechado con alto contenido de jugo. Ideal para jugos, postres y cócteles naturales.',
    beneficios: ['Tranquilizante natural', 'Rico en vitamina C', 'Fortalece el sistema inmune', 'Antioxidante'],
    imagenURL: 'https://images.unsplash.com/photo-1604500000006-5b4d552b7d31?w=600&q=80',
  },
  {
    fincaId: 'finca-1',
    fincaNombre: 'Agroparque Los Manantiales',
    nombre: 'Guanábana Fresca',
    categoria: 'Frutas',
    precio: 12000,
    unidad: 'unidad',
    stock: 20,
    descripcion: 'Guanábana de primera calidad, cremosa y aromática. Perfecta para jugos, helados artesanales o consumo directo.',
    beneficios: ['Propiedades anticancerígenas estudiadas', 'Fuente de vitamina B', 'Regula azúcar en sangre', 'Antiinflamatorio'],
    imagenURL: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&q=80',
  },
  // Finca 3 — El Vergel del Río (índice 2)
  {
    fincaId: 'finca-2',
    fincaNombre: 'El Vergel del Río',
    nombre: 'Plátano Hartón Verde',
    categoria: 'Tubérculos',
    precio: 3500,
    unidad: 'racimo',
    stock: 30,
    descripcion: 'Plátano hartón cosechado en el punto exacto de madurez para cocinar. Ideal para patacones, sancocho y aborrajado.',
    beneficios: ['Alto en carbohidratos', 'Fuente de potasio', 'Sin azúcares añadidos', 'Energía duradera'],
    imagenURL: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=600&q=80',
  },
  {
    fincaId: 'finca-2',
    fincaNombre: 'El Vergel del Río',
    nombre: 'Yuca Criolla Fresca',
    categoria: 'Tubérculos',
    precio: 2800,
    unidad: 'kg',
    stock: 90,
    descripcion: 'Yuca blanca criolla recién arrancada, suave y harinosa. La base de la cocina costeña: sancochos, carimañolas y más.',
    beneficios: ['Libre de gluten', 'Alta en almidón resistente', 'Prebiótico natural', 'Energizante'],
    imagenURL: 'https://images.unsplash.com/photo-1612204103590-b35fe5d09c65?w=600&q=80',
  },
  // Finca 4 — Santa Rosa (índice 3)
  {
    fincaId: 'finca-3',
    fincaNombre: 'Finca Santa Rosa',
    nombre: 'Pimentón Rojo Premium',
    categoria: 'Hortalizas',
    precio: 5500,
    unidad: 'kg',
    stock: 45,
    descripcion: 'Pimentón rojo maduro, carnoso y brillante. Cultivado con técnicas regenerativas que concentran el sabor y los nutrientes.',
    beneficios: ['Muy alto en vitamina C', 'Fuente de betacarotenos', 'Antiinflamatorio', 'Bajo en calorías'],
    imagenURL: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&q=80',
  },
  {
    fincaId: 'finca-3',
    fincaNombre: 'Finca Santa Rosa',
    nombre: 'Ají Criollo Picante',
    categoria: 'Especias',
    precio: 3000,
    unidad: '250g',
    stock: 35,
    descripcion: 'Ají criollo del Atlántico, con ese picor característico y aroma floral. Imprescindible en la cocina costeña auténtica.',
    beneficios: ['Acelera el metabolismo', 'Antimicrobiano natural', 'Fuente de capsaicina', 'Analgésico natural'],
    imagenURL: 'https://images.unsplash.com/photo-1444731961956-751ed90465a5?w=600&q=80',
  },
]

export const CATEGORIAS = [
  { id: 'todas', nombre: 'Todos', icono: '🌾' },
  { id: 'Hortalizas', nombre: 'Hortalizas', icono: '🥬' },
  { id: 'Frutas', nombre: 'Frutas', icono: '🥭' },
  { id: 'Tubérculos', nombre: 'Tubérculos', icono: '🍠' },
  { id: 'Hierbas', nombre: 'Hierbas', icono: '🌿' },
  { id: 'Especias', nombre: 'Especias', icono: '🌶️' },
]
